/*
 * This represents the data needed to fetch courses from Duke's catalog API.
 *
 * @author Abby Mapes
 */

// Taken from Duke's course catalog website
const subjects = ['AAAS - African & African Amer Studies',
    'AEROSCI - Aerospace Studies-AFROTC',
    'AMES - Asian & Middle Eastern Studies',
    'ARABIC - Arabic',
    'ARTHIST - Art History',
    'ARTS&SCI - Arts and Science IDEAS themes',
    'ARTSVIS - Visual Arts',
    'BALTFIN - Balto-Finnic',
    'BIOCHEM - Biochemistry',
    'BIOETHIC - Bioethics and Science Policy',
    'BIOLOGY - Biology',
    'BME - Biomedical Engineering',
    'BRAINSOC - Brain & Society',
    'CEE - Civil and Environmental Egr',
    'CELLBIO - Cell Biology',
    'CESC - Civic Engagement&Social Change',
    'CHEM - Chemistry',
    'CHILDPOL - Child Policy',
    'CHINESE - Chinese',
    'CLST - Classical Studies',
    'CMAC - Cmputnl Media, Arts & Cultures',
    'COMPSCI - Computer Science',
    'CREOLE - Creole',
    'CULANTH - Cultural Anthropology',
    'DANCE - Dance',
    'DECSCI - Decision Sciences Program',
    'DOCST - Documentary Studies',
    'ECE - Electrical & Computer Egr',
    'ECON - Economics',
    'EDUC - Education',
    'EGR - Engineering',
    'EHD - Education and Human Developmnt',
    'ENERGY - Energy',
    'ENGLISH - English',
    'ENRGYEGR - Energy Engineering',
    'ENVIRON - Environment',
    'EOS - Earth and Ocean Sciences',
    'ETHICS - Study of Ethics',
    'EVANTH - Evolutionary Anthropology',
    'FRENCH - French',
    'GENOME - Genome Sciences and Policy',
    'GERMAN - German',
    'GLHLTH - Global Health',
    'GREEK - Greek',
    'GSF - Gender Sexuality & Feminist St',
    'HEBREW - Hebrew',
    'HINDI - Hindi',
    'HISTORY - History',
    'HLTHPOL - Health Policy',
    'HOUSECS - House Course',
    'HUMANDEV - Human Development',
    'I&E - Innovation & Entrepreneurship',
    'ICS - Internatl Comparative Studies',
    'IDS - Interdisciplinary Data Science',
    'IMMUNOL - Immunology',
    'ISS - Information Science + Studies',
    'ITALIAN - Italian',
    'JEWISHST - Jewish Studies',
    'JPN - Japanese',
    "KICHE - K'iche' Maya",
    'KOREAN - Korean',
    'LATAMER - Latin American Studies',
    'LATIN - Latin',
    'LINGUIST - Linguistics',
    'LIT - Literature',
    'LSGS - Latino Studies Global South',
    'MATH - Mathematics',
    'MEDREN - Medieval and Renaissance',
    'MGM - Molec Genetics & Microbiology',
    'MILITSCI - Military Science (Army ROTC)',
    'MMS - Markets and Management Studies',
    'MUSIC - Music',
    'NAVALSCI - Naval Science (Navy ROTC)',
    'NEUROBIO - Neurobiology',
    'NEUROSCI - Neuroscience',
    'PATHOL - Pathology',
    'PERSIAN - Persian',
    'PHARM - Pharm and Cancer Biology',
    'PHIL - Philosophy',
    'PHYSEDU - Physical Education',
    'PHYSICS - Physics',
    'PJMS - Policy Journalism and Media St',
    'POE - Practice-Oriented Education',
    'POLISH - Polish',
    'POLSCI - Political Science',
    'PORTUGUE - Portuguese',
    'PSY - Psychology',
    'PUBPOL - Public Policy',
    'QUECHUA - Quechua',
    'REG - Registration',
    'RELIGION - Religion',
    'RIGHTS - Human Rights',
    'ROMANIAN - Romanian',
    'ROMST - Romance Studies',
    'RUSSIAN - Russian',
    'SANSKRIT - Sanskrit',
    'SCISOC - Science & Society',
    'SERBCRO - Serbian and Croatian',
    'SES - Slavic and Eurasian Studies',
    'SOCIOL - Sociology',
    'SPANISH - Spanish',
    'STA - Statistical Science',
    'SUSTAIN - Sustainability Engagement',
    'SXL - Study of Sexualities',
    'THEATRST - Theater Studies',
    'TIBETAN - Tibetan',
    'TURKISH - Turkish',
    'UKRAIN - Ukrainian',
    'URDU - Urdu',
    'UZBEK - Uzbek',
    'VMS - Visual and Media Studies',
    'WRITING - Writing'];

exports.subjects = subjects;
